name: Build, Version Update, and Changelog Update

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: 9.3.0

      - name: Install dependencies
        run: pnpm install

      - name: Update version
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ "feat" ]]; then
            npm version minor
          elif [[ "${{ github.event.head_commit.message }}" =~ "fix" ]]; then
            npm version patch
          else
            npm version patch
          fi

      - name: Generate Changelog
        run: npx conventional-changelog-cli -p angular -i changelog.md -s

      - name: Build project
        run: pnpm run build

      # - name: Commit and Push Changes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add changelog.md package.json pnpm-lock.yaml
      #     git commit -m "chore: update changelog and version to $(node -p \"require('./package.json').version\")"
      #     git push origin master

      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag v$(node -p "require('./package.json').version")
          git push origin v$(node -p "require('./package.json').version")

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: 'v$(node -p "require(''./package.json'').version")'
          release_name: 'Release v$(node -p "require(''./package.json'').version")'
          body: |
            See the changelog for more details.
          draft: false
          prerelease: false
